package traffic.wcf.bss.com.bskyb.mamrequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2015-04-29T16:39:29.635+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://BSkyB.com.BSS.WCF.Traffic/MAMRequest", name = "IRequest")
@XmlSeeAlso({common.bss.com.bskyb.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, traffic.contract.bss.com.bskyb.request.ObjectFactory.class, traffic.contract.bss.com.bskyb.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IRequest {

    @WebMethod(operationName = "Update", action = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/Update")
    @Action(input = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/Update", output = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/UpdateResponse", fault = {@FaultAction(className = IRequestUpdateBusinessExceptionFaultFaultMessage.class, value = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/UpdateBusinessExceptionFault")})
    @WebResult(name = "UpdateResponse", targetNamespace = "http://BSkyB.com.BSS.Contract.Traffic/Request", partName = "request")
    public traffic.contract.bss.com.bskyb.request.UpdateResponse update(
        @WebParam(partName = "request", name = "Update", targetNamespace = "http://BSkyB.com.BSS.Contract.Traffic/Request")
        traffic.contract.bss.com.bskyb.request.Update request
    ) throws IRequestUpdateBusinessExceptionFaultFaultMessage;

    @WebMethod(operationName = "Get", action = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/Get")
    @Action(input = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/Get", output = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/GetResponse", fault = {@FaultAction(className = IRequestGetBusinessExceptionFaultFaultMessage.class, value = "http://BSkyB.com.BSS.Contract.Traffic/Request/IRequest/GetBusinessExceptionFault")})
    @WebResult(name = "GetResponse", targetNamespace = "http://BSkyB.com.BSS.Contract.Traffic/Request", partName = "request")
    public traffic.contract.bss.com.bskyb.request.GetResponse get(
        @WebParam(partName = "request", name = "Get", targetNamespace = "http://BSkyB.com.BSS.Contract.Traffic/Request")
        traffic.contract.bss.com.bskyb.request.Get request
    ) throws IRequestGetBusinessExceptionFaultFaultMessage;
}
